# ====================================================
# CONFIGURACIÓN DEL SERVIDOR
# ====================================================
server.port=8085
server.address=0.0.0.0
# ====================================================
# BASE DE DATOS LOCAL (XAMPP)
# DESCOMENTAR SI QUIERES VOLVER A TU MYSQL LOCAL
# ====================================================
# MySQL
#/spring.datasource.url=jdbc:mysql://localhost:3306/neurotutor_db?useSSL=false&serverTimezone=America/Lima
#spring.datasource.username=root
#spring.datasource.password=
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect//

# ====================================================
# BASE DE DATOS RAILWAY
# ACTIVAR PARA PROBAR LA CONEXIÓN REMOTA
# ====================================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# ====================================================
# JPA / HIBERNATE
# ====================================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ==================== CONFIGURACIÓN DE CORREO CON GMAIL ====================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
# Coloca aquí tu correo personal de Gmail
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

# Propiedades obligatorias de seguridad para Gmail (TLS)
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
# ? TIEMPOS DE ESPERA PARA EL CORREO (Añadir al final de tu archivo)
spring.mail.properties.mail.smtp.connectiontimeout=3000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=3000

# ==================== JWT CONFIG ====================
jwt.secret=neurotutor_secret_key_2026_muy_segura
jwt.expiration=36000